# Generated by Django 2.2.4 on 2019-10-12 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinationpage_use_destination_name_as_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationpage',
            name='lat_long',
            field=models.CharField(blank=True, help_text="Comma separated lat/long. (Ex. 64.144367, -21.939182)                    Right click Google Maps and select 'What's Here'", max_length=36, null=True, validators=[django.core.validators.RegexValidator(code='invalid_lat_long', message='Lat Long must be a comma-separated numeric lat and long', regex='^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$')]),
        ),
    ]
