# Generated by Django 2.2.4 on 2019-09-01 16:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteampage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
