# Generated by Django 2.2.4 on 2019-09-01 17:28

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_ourteampage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteampage',
            name='body',
        ),
        migrations.AddField(
            model_name='ourteampage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional text', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourteampage',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
