# Generated by Django 2.2.4 on 2019-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0003_auto_20190901_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteampage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
