# Generated by Django 2.2.4 on 2019-11-23 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tours', '0009_tourdestinationorderable'),
        ('ourteam', '0006_auto_20191123_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourGuide',
            new_name='TourGuidePage',
        ),
    ]
