# Generated by Django 2.2.4 on 2019-11-23 15:51

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0007_auto_20191123_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetoursorderable',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_tours', to='ourteam.TourGuidePage'),
        ),
    ]
