# Generated by Django 2.2.4 on 2019-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0008_auto_20191123_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguidepage',
            name='allow_direct_guide_booking',
            field=models.BooleanField(help_text='wether this guide agrees to be booked for an hourly rate plus additional charge'),
        ),
        migrations.AlterField(
            model_name='tourguidepage',
            name='hourly_rate_high_season',
            field=models.DecimalField(decimal_places=2, help_text='hourly rate high season', max_digits=4),
        ),
        migrations.AlterField(
            model_name='tourguidepage',
            name='hourly_rate_low_season',
            field=models.DecimalField(decimal_places=2, help_text='hourly rate low season', max_digits=4),
        ),
    ]
