# Generated by Django 2.2.4 on 2019-11-23 17:17

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0009_auto_20191123_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=127)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify guides by this qualification', max_length=127, verbose_name='slug')),
            ],
            options={
                'ordering': ['qualification'],
                'verbose_name_plural': 'Guide Qualifications',
                'verbose_name': 'Guide Qualification',
            },
        ),
        migrations.AddField(
            model_name='tourguidepage',
            name='qualifications',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='ourteam.GuideQualification'),
        ),
    ]
