# Generated by Django 2.2.4 on 2019-11-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0010_auto_20191123_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguidepage',
            name='intro',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
