# Generated by Django 2.2.4 on 2019-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0012_auto_20191124_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguidepage',
            name='additional_charge_per_tour',
        ),
        migrations.AddField(
            model_name='tourguidepage',
            name='additional_charge_per_day',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='added charge per group for each day', max_digits=4),
        ),
    ]
