# Generated by Django 2.2.4 on 2019-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpage',
            options={'verbose_name': 'Tour information Page', 'verbose_name_plural': 'Tour information Pages'},
        ),
        migrations.AlterModelOptions(
            name='toursindexpage',
            options={'verbose_name': 'Tours Index Page', 'verbose_name_plural': 'Tours Index Pages'},
        ),
        migrations.AddField(
            model_name='tourpage',
            name='price_high_season',
            field=models.IntegerField(blank=True, help_text='enter the price for the group on high season time [$]', null=True),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='price_low_season',
            field=models.IntegerField(blank=True, help_text='enter the price for the group on low season time [$]', null=True),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='tour_duration',
            field=models.DurationField(blank=True, help_text='enter the approximate duration usual for this tour', null=True),
        ),
    ]
