# Generated by Django 2.2.4 on 2019-10-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20191003_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='max_num_people',
            field=models.IntegerField(blank=True, help_text='enter the maximum group size of people', null=True),
        ),
    ]
