# Generated by Django 2.2.4 on 2019-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourpage_max_num_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('slug', models.SlugField(allow_unicode=True, help_text='A slug to identify tours by this category', max_length=127, verbose_name='slug')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
            },
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourprovince',
            name='province_name',
            field=models.CharField(max_length=31),
        ),
    ]
