# Generated by Django 2.2.4 on 2019-10-04 10:16

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20191004_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='tours.TourCategory'),
        ),
    ]
