# Generated by Django 2.2.4 on 2019-10-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('tours', '0006_tourcategoryindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourCategoryIndexPage',
        ),
    ]
