# Generated by Django 2.2.9 on 2019-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourdestinationorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourprovince',
            name='province_website',
        ),
        migrations.AddField(
            model_name='tourprovince',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='slug', help_text='A slug to identify tours by this category', max_length=31, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
