# Generated by Django 2.2.9 on 2019-12-29 16:47

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20191229_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='provinces',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='tours.TourProvince'),
        ),
    ]
