# Generated by Django 2.2.9 on 2019-12-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tourpage_provinces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpage',
            name='provinces',
        ),
    ]
