# Generated by Django 2.2.9 on 2019-12-29 21:09

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_remove_tourpage_provinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='provinces',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='tours.TourProvince'),
        ),
        migrations.DeleteModel(
            name='TourProvincesOrderable',
        ),
    ]
