# Generated by Django 2.2.4 on 2019-09-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='tags',
        ),
    ]
