# Generated by Django 2.2.4 on 2019-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogtagindexpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='Wolfgang Pirker', max_length=64),
            preserve_default=False,
        ),
    ]
