# Generated by Django 2.2.4 on 2019-10-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogauthorsorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
    ]
